modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (31 is current forge version)
credits="Drachenbauer32" #optional
authors="Drachenbauer32" #optional

[[mods]] #mandatory
modId="balloonmod" #mandatory
version="0.1.0" #mandatory
displayName="Balloon Mod" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Decorative balloons for minecraft
'''

[[dependencies.balloonmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
# Here's another dependency
[[dependencies.balloonmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
	side="BOTH"
